AllCops:
  Exclude:
    - 'tmp/*'
Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

ClassLength:
  Max: 200

AccessModifierIndentation:
  EnforcedStyle: outdent

IfUnlessModifier:
  Enabled: false

CaseIndentation:
  IndentWhenRelativeTo: case
  IndentOneStep: true

MethodLength:
  CountComments: false
  Max: 20

SignalException:
  Enabled: false

ColonMethodCall:
  Enabled: false

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

ClassVars:
  Enabled: false

RegexpLiteral:
  Enabled: false

RedundantBegin:
  Enabled: false

AssignmentInCondition:
  Enabled: false

ParameterLists:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

DoubleNegation:
  Enabled: false

TrivialAccessors:
  ExactNameMatch: true

AbcSize:
  Max: 30
